#!/bin/bash

(
  git remote rm origin
  git remote add origin https://$CI_USER_PAT@github.com/drashland/deno-drash-docs.git
  git config user.email $CI_USER_EMAIL
  git config user.name $CI_USER_NAME
  git pull origin master
)
