#!/bin/bash
#
# All env variables should be set before running this script
#

(
  export DENO_DRASH_DOCS_ENVIRONMENT="production"
  git config user.name "drashbot"
  git config user.email "drash.crooks@gmail.com"
  console/run_webpack --env.environment="production"
  console/compile_assets
  console/compile_ejs_templates
  git add .
  git commit -m "$(date) - manual build"
)
