<script>
  import H2Hash from "/assets/common/vue/h2_hash.vue";
  import Page from "/assets/common/vue/page.vue";
  import CodeBlock from "/assets/common/vue/code_block.vue";

  const title = "Automate Updating Dependencies";

  const token = "${{ secrets.TOKEN }}"

  export const resource = {
    paths: [
      "/tutorials/automate-updating-dependencies",
    ],
    meta: {
      title: title
    }
  }

  export default {
    components: {
      CodeBlock,
      H2Hash,
      Page,
    },
    data() {
      return {
        base_url: this.$conf.dmm.base_url,
        title: title,
        toc: [
          "Description",
          "Example",
        ],
        token: token
      };
    }
  }
</script>

<template lang="pug">
page(
  :base_url="base_url"
  :title="title"
  :toc="toc"
)
  h2-hash Description
  p You can use Dmm to automatically update your dependencies. As Dmm can update dependencies, all you need is a new workflow, and every Sunday, the workflow will run, update your dependencies (if they can be) and make a pull request for you to review!
  p Note: This tutorial will explain how to use Dmm as a 'bumper', but will not explain the ins and outs of a workflow file. For this, refer to GitHub's documentation.
  hr
  h2-hash Example
  code-block(title=".github/workflows/bumper.yml" language="yaml")
    | name: Update dependencies and bump version numbers
    |
    | on:
    |   schedule:
    |     # Runs at 00:00 UTC every day
    |     - cron: '0 0 * * *'
    |
    | jobs:
    |
    |   update:
    |     runs-on: ubuntu-latest
    |     steps:
    |     - uses: actions/checkout@v2
    |
    |     - name: Install Deno
    |       uses: denolib/setup-deno@master
    |
    |     - name: Update dmm
    |       run: |
    |         deno run --allow-read --allow-write --allow-net https://deno.land/x/dmm/mod.ts update
    |         cd tests
    |         deno run --allow-read --allow-write --allow-net https://deno.land/x/dmm/mod.ts update
    |
    |     - name: Create pull request
    |       uses: peter-evans/create-pull-request@v3
    |       with:
    |         token: {{ token }}
    |         commit-message: 'Update dependencies'
    |         title: 'chore: Update dependencies'
    |         body: 'This pull request was auto-generated by GitHub Actions.'
    |         branch: update-dependencies
  p Here, you ca use Dmm to update your dependencies in your repository automatically, every day and create a pull request. That way, you never have to do this manually, and you will know when your dependencies need updating because you will see a notification that a pull request was opened!
  p Of course, if there are no dependencie to update, Dmm will not change any files. If no files are modified, then a pull request will not be made, and there are no changes to commit.
</template>

