#!/bin/bash

echo -e "Building production environment files\n"

# Compile dmm production environment
node scripts/dmm_compile_vue_routes.js

# Compile Drash production environment
node scripts/drash_compile_example_code.js
node scripts/drash_compile_vue_global_components.js
node scripts/drash_compile_vue_routes.js

# Compile Rhum production environment
node scripts/rhum_compile_vue_routes.js

# Compile Sockets production environment
node scripts/sockets_compile_vue_routes.js

# Compile Cinco production environment
node scripts/cinco_compile_vue_routes.js

# Compile all html files for all modules
node scripts/compile_production_html.js

# Build webpack bundles
node_modules/.bin/webpack --hide-modules --env.environment=production
