#!/bin/bash

echo -e "Building Drash Staging environment\n"

# Compile all data used by Vue
node scripts/drash_compile_example_code.js
node scripts/drash_compile_vue_global_components.js
node scripts/drash_compile_vue_routes.js

# Compile staging index.html
node scripts/drash_compile_staging_index_html.js

# Build webpack bundles
node_modules/.bin/webpack --env.environment=staging --hide-modules
