#!/bin/bash
#
# All env variables should be set before running this script
#

(
  export DENO_DRASH_DOCS_ENVIRONMENT="production"
  cp conf/app.ci.ts conf/app.ts
  console/compile_assets
  console/compile_templates
  console/run_webpack --env.environment="production"
)
