#!/bin/bash

(
  echo "Performing production compilation of webpack bundle.js"

  node_modules/.bin/webpack \
    --env.base_url="/deno-drash" \
    --env.build_date="$(date)" \
    --env.deno_version="$(deno --version)" \
    --env.environment="production" \
    --env.latest_release="v0.27.4" \
    --hide-modules

  echo "Done."

  echo "Performing build using build.ts ..."

  deno --allow-all ./build.ts

  echo "Done."

  echo "Performing git commit ..."

  git add index.html
  git add public/assets/js/bundle.min.js
  git commit -m "npm run build ($(date))"

  echo "Done."

  echo "Build is ready to be pushed to the repository"
)
