#!/bin/bash

BRANCH="$(git branch --show-current)"
PARENT_BRANCH="$1"

echo -e "Building bundles for $BRANCH under $PARENT_BRANCH"

node console/compile_vue_routes.js $PARENT_BRANCH

node_modules/.bin/webpack \
  --config ./configs.webpack.production.js \
  --hide-modules \
  --env.branch=$PARENT_BRANCH \
