#!/bin/bash

(
  echo "Performing production compilation of webpack bundle.js"

  ./webpack

  echo "Done."

  echo "Performing build using build.ts ..."

  deno --allow-all ./build.ts

  echo "Done."

  echo "Performing git commit ..."

  git add index.html
  git add public/assets/js/bundle.min.js
  git commit -m "npm run build ($(date))"

  echo "Done."

  echo "Build is ready to be pushed to the repository"
)
