#!/bin/bash

MODULE="$1"
VERSION="$2"

echo -e "Building version files for $MODULE@$VERSION\n"

console/compile_vue_routes $MODULE

node_modules/.bin/webpack \
  --config ./configs.webpack.production.js \
  --hide-modules \
  --env.environment=version \
  --env.mode=production \
  --env.module=$MODULE \
  --env.version=$VERSION
