#!/bin/bash
#
# DOCS_BASE_URL will be appended to drashland.github.io (e.g., drashland.github.io/deno-drash-docs)
#

(
  echo -n "Compiling .ejs templates to .html files ..."
  deno --allow-read --allow-write --allow-env --allow-net ./compile_ejs_templates.ts
  echo "... done."
)
