#!/bin/bash

MODULE="$1"

if [ $MODULE ]; then
  node console/compile_vue_routes.js $MODULE
  exit
fi

node console/compile_vue_routes.js dmm
node console/compile_vue_routes.js drash
node console/compile_vue_routes.js rhum
node console/compile_vue_routes.js wocket
