#!/bin/bash
#
# DOCS_BASE_URL will be appended to drashland.github.io (e.g., drashland.github.io/deno-drash-docs)
#

(
  export DENO_DRASH_DOCS_ENVIRONMENT="$1"
  echo -n "Compiling .ejs templates to .html files ..."
  deno --allow-read --allow-write --allow-env --allow-net console/ts/compile_ejs_templates.ts
  echo "... done."
)
