#!/bin/bash

(
  echo -n "Compiling Vue global components ..."
  deno --allow-read --allow-write --allow-env --allow-net console/ts/compile_vue_global_components.ts
  echo "... done."

  echo -n "Compiling Vue route components ..."
  deno --allow-read --allow-write --allow-env --allow-net console/ts/compile_vue_route_components.ts
  echo "... done."
)
