#!/bin/bash

(
  npm run dev-docs
  watchmedo shell-command \
    --command='npm run dev-docs -- restart' \
    --recursive \
    --drop \
    --ignore-directories \
    --patterns="*.ts;*.json;*/console/*/*;*.vue;*.js;*.ejs" \
    --ignore-pattern="*/compiled_*.json;*/compiled_*.js;*/compiled_routes.js;*/api_reference.json;*/.#*.ts;*.swp" \
    ./
)
