#!/bin/bash

(
  export DENO_DRASH_DOCS_ENVIRONMENT="development"

  console/run_dev_server

  # Run watchdog so it can reload the server on file changes
  watchmedo shell-command \
    --command='console/run_dev_server restart-by-watchdog' \
    --drop \
    --ignore-directories \
    --ignore-pattern="*/compiled_*.json;*/compiled_*.js;*/compiled_routes.js;*/api_reference.json;*/.#*.ts;*.swp;bundle_app_data.js" \
    --patterns="*.ts;*.json;*/console/*/*;*.vue;*.js;*.ejs" \
    --recursive \
    ./
)
