#!/bin/bash
#
# DOCS_BASE_URL will be appended to drashland.github.io (e.g., drashland.github.io/deno-drash-docs)
#

(
  export DOCS_BASE_URL=""
  export DOCS_ENVIRONMENT="development"

  console/dev_kill

  console/delete_ds_store

  console/compile_assets

  # Are we restarting or now just starting up?
  if [[ $1 == "restart-by-watchdog" ]]; then
    echo -n "[watchdog] Restarting docs.ts app ..."
  else
    echo -n "[watchdog] Starting docs.ts app ..."
  fi
  deno --allow-read --allow-write --allow-env --allow-net ./docs.ts &
  echo "... done."

  echo -e "[watchdog] Make sure you are running webpack:"
  echo -e "\n    \`npm run dev-webpack -- --watch\`\n"
)
