#!/bin/bash
#
# DOCS_BASE_URL will be appended to drashland.github.io (e.g., drashland.github.io/deno-drash-docs)
#

(
  console/delete_ds_store
  console/compile_assets
  console/run_webpack --env.environment="staging"
  console/compile_index_ejs "staging"

  cp -r index.html staging/index.html
  cp -r public staging

  git checkout -- index.html
  git checkout -- public/*

  echo -e "Build is ready to be pushed to the repository."
)
