#!/bin/bash

(
  export DENO_DRASH_DOCS_ENVIRONMENT="production"

  console/delete_ds_store
  console/compile_assets
  console/run_webpack --env.environment="$DENO_DRASH_DOCS_ENVIRONMENT"
  console/compile_ejs_templates

  echo -e "Done building production-ready files."
  echo -e "\n    \`console/deploy && git push\`"
)
