#!/bin/bash

(
  export DENO_DRASH_DOCS_ENVIRONMENT="production"

  console/delete_ds_store
  console/compile_assets
  console/run_webpack --env.environment="$DENO_DRASH_DOCS_ENVIRONMENT"
  console/compile_ejs_templates

  echo -e "Build is ready to be pushed to the repository."
  echo -e "\n    Use \`console/deploy\`"
)
