#!/bin/bash
#
# --env.base_url is only used in non-prod environments
#

(
  watchmedo shell-command \
    --command='console/dev_docs restart-by-watchdog' \
    --drop \
    --ignore-directories \
    --ignore-pattern="*/compiled_*.json;*/compiled_*.js;*/compiled_routes.js;*/api_reference.json;*/.#*.ts;*.swp;bundle_app_data.js" \
    --patterns="*.ts;*.json;*/console/*/*;*.vue;*.js;*.ejs" \
    --recursive \
    ./
)
