#!/bin/bash

(
  console/dev_kill
  console/delete_ds_store
  console/compile_assets

  # Are we restarting or now just starting up?
  if [[ $1 == "restart-by-watchdog" ]]; then
    echo -n "[watchdog] Restarting docs.ts app ..."
  else
    echo -n "[watchdog] Starting docs.ts app ..."
  fi
  deno --allow-read --allow-write --allow-env --allow-net ./docs.ts &
  echo "... done."

  echo -e "[watchdog] Make sure you run webpack:"
  echo -e "\n    Single compilations:"
  echo -e "\n    \`npm run webpack\`\n"
  echo -e "\n    Continuous compilations:"
  echo -e "\n    \`npm run webpack -- --watch\`\n"
)
