#!/bin/bash

(
  echoEnv() {
    echo -e "  $1"
  }

  echo -e "Setting environment variables ...\n"

  export DENO_DRASH_DOCS_LATEST_RELEASE="$(git tag | sort -V)"
  export DENO_DRASH_LATEST_RELEASE="v$(git ls-remote --tags https://github.com/drashland/deno-drash.git | awk '{print $2}' | sort -V | tail -1 | sed 's/refs.*v//g')"

  echoEnv "DENO_DRASH_DOCS_LATEST_RELEASE: $DENO_DRASH_DOCS_LATEST_RELEASE"
  echoEnv "DENO_DRASH_LATEST_RELEASE:      $DENO_DRASH_LATEST_RELEASE"

  echo -e "\n... done."
)
