#!/bin/bash

(
  export DENO_DRASH_DOCS_ENVIRONMENT="staging"

  console/delete_ds_store
  console/compile_assets
  console/run_webpack --env.environment="$DENO_DRASH_DOCS_ENVIRONMENT"
  console/compile_ejs_templates

  # Clean that shit up
  rm -rf staging/public/*
  mkdir -p staging/public/assets
  mkdir staging/public/assets/css
  mkdir staging/public/assets/img
  mkdir staging/public/assets/js
  mkdir staging/public/assets/vendor

  # Copy what was build for prod env; use for the staging env
  cp    index.html staging/index.html
  cp    public/assets/css/style-docs.css     staging/public/assets/css/style-docs.css
  cp    public/assets/css/style-docs.css.map staging/public/assets/css/style-docs.css.map
  cp    public/assets/js/bundle.staging.js   staging/public/assets/js/bundle.staging.js
  cp    public/assets/js/app_data.staging.js staging/public/assets/js/app_data.staging.js
  cp -r public/assets/img                  staging/public/assets/
  cp -r public/assets/vendor               staging/public/assets/

  # Discard changes made to the prod env
  git checkout -- index.html
  git checkout -- public/*


  echo -n "Committing to repository ..."
  git add staging/*
  git commit -m "build/deploy staging ($(date))"
  echo "... done."

  echo -n "Pushing to repository ..."
  git push
  echo "... done."
)
